image:
  file: .gitpod.dockerfile
tasks:
  - name: Forem Server
    before: |
      redis-server &
  - init: yarn
  - command: >
      while [ -z "$TOKEN" ] ; do
        printf "\n❗ The TOKEN environment variable is required. Please enter its value.\n" &&
        read -s -p "TOKEN: " TOKEN ;
      done ; gp env TOKEN=$TOKEN && printf "\nThanks\n"
      # Now you can use $TOKEN
